
import React, { useState } from 'react';
import SynapseLogo from './icons/SynapseLogo';
import ArrowRightIcon from './icons/ArrowRightIcon';

interface PrivacyPolicyProps {
    onNavigate: (view: 'landing') => void;
}

const Section: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => (
    <div className="mb-8">
        <h2 className="text-2xl font-bold text-white mb-3">{title}</h2>
        <div className="space-y-4 text-slate-400 prose prose-invert prose-sm max-w-none">
            {children}
        </div>
    </div>
);

const PrivacyPolicy: React.FC<PrivacyPolicyProps> = ({ onNavigate }) => {
    return (
        <div className="min-h-screen bg-slate-950 text-white p-4 sm:p-6 lg:p-8">
            <div className="max-w-4xl mx-auto">
                <header className="text-center mb-12">
                    <SynapseLogo className="w-12 h-12 mx-auto mb-4" />
                    <h1 className="text-4xl font-extrabold gradient-text">Privacy Policy</h1>
                    <p className="text-slate-400 mt-2">Last Updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
                </header>

                <main>
                    <Section title="1. Introduction">
                        <p>Synapse AI ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our Service. By using the Service, you agree to the collection and use of information in accordance with this policy.</p>
                    </Section>
                    
                    <Section title="2. Information We Collect">
                        <p>We may collect personal information that you provide to us directly, such as:</p>
                        <ul>
                            <li><strong>Account Information:</strong> When you register for an account, we collect your email address, name, and password.</li>
                            <li><strong>User Content:</strong> We collect the inputs you provide to the AI models and the content generated by the service (outputs). This includes your Brand Profile information and any text, images, or other data you submit.</li>
                            <li><strong>Payment Information:</strong> For users on paid plans, we use a third-party payment processor (like Stripe). We do not store your credit card details ourselves.</li>
                        </ul>
                        <p>We also collect some information automatically:</p>
                        <ul>
                            <li><strong>Usage Data:</strong> We log information about your interactions with our Service, such as the features you use, generations performed, and error data.</li>
                        </ul>
                    </Section>
                    
                    <Section title="3. How We Use Your Information">
                        <p>We use the information we collect to:</p>
                        <ul>
                            <li>Provide, maintain, and improve our Service.</li>
                            <li>Process your transactions and manage your subscription.</li>
                            <li>Communicate with you, including sending service-related notices and responding to your inquiries.</li>
                            <li>Monitor and analyze usage and trends to improve your experience.</li>
                            <li>To train and improve our models. We may use your inputs and outputs for this purpose. You can opt-out of this by contacting our support team.</li>
                        </ul>
                    </Section>
                    
                    <Section title="4. How We Share Your Information">
                        <p>We do not sell your personal information. We may share your information in the following limited circumstances:</p>
                        <ul>
                            <li><strong>With Service Providers:</strong> We may share information with third-party vendors and services that help us operate our Service, such as cloud hosting (Firebase) and payment processing.</li>
                            <li><strong>For Legal Reasons:</strong> We may disclose your information if we believe it's required by law, subpoena, or other legal process.</li>
                        </ul>
                    </Section>
                    
                    <Section title="5. Data Security">
                        <p>We implement a variety of security measures to maintain the safety of your personal information. We use Firebase, a Google Cloud platform, which provides robust security for data storage and authentication. However, no electronic transmission or storage is 100% secure, and we cannot guarantee its absolute security.</p>
                    </Section>
                    
                    <Section title="6. Your Data Rights">
                        <p>Depending on your location, you may have rights to access, correct, or delete your personal information. You can manage your account information through your settings page or by contacting us directly.</p>
                    </Section>
                    
                    <Section title="7. Changes to This Privacy Policy">
                        <p>We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last Updated" date. You are advised to review this Privacy Policy periodically for any changes.</p>
                    </Section>
                </main>

                <footer className="text-center mt-12">
                    <button onClick={() => onNavigate('landing')} className="inline-flex items-center text-slate-300 hover:text-white font-semibold py-2 px-4 rounded-lg transition-colors duration-300">
                        Back to Home
                        <ArrowRightIcon className="w-4 h-4 ml-2" />
                    </button>
                </footer>
            </div>
        </div>
    );
};

export default PrivacyPolicy;