
import React, { useState } from 'react';
import SynapseLogo from './icons/SynapseLogo';
import ArrowRightIcon from './icons/ArrowRightIcon';

interface TermsAndConditionsProps {
    onNavigate: (view: 'landing') => void;
}

const Section: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => (
    <div className="mb-8">
        <h2 className="text-2xl font-bold text-white mb-3">{title}</h2>
        <div className="space-y-4 text-slate-400 prose prose-invert prose-sm max-w-none">
            {children}
        </div>
    </div>
);

const TermsAndConditions: React.FC<TermsAndConditionsProps> = ({ onNavigate }) => {
    return (
        <div className="min-h-screen bg-slate-950 text-white p-4 sm:p-6 lg:p-8">
            <div className="max-w-4xl mx-auto">
                <header className="text-center mb-12">
                    <SynapseLogo className="w-12 h-12 mx-auto mb-4" />
                    <h1 className="text-4xl font-extrabold gradient-text">Terms of Service</h1>
                    <p className="text-slate-400 mt-2">Last Updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
                </header>

                <main>
                    <Section title="1. Introduction">
                        <p>Welcome to Synapse AI ("we," "our," or "us"). These Terms of Service ("Terms") govern your access to and use of our website, services, and applications (collectively, the "Service"). By accessing or using the Service, you agree to be bound by these Terms. If you do not agree to these Terms, you may not use the Service.</p>
                    </Section>

                    <Section title="2. Use of the Service">
                        <p>You may use the Service only in compliance with these Terms and all applicable laws. You must be at least 13 years old to use the Service. By creating an account, you agree to provide accurate and complete information and to keep this information up to date.</p>
                        <p>Our "Freemium" plan is provided for personal and evaluation purposes. Our "Pro" and "Enterprise" plans grant you a license to use the generated content for commercial purposes, subject to the restrictions outlined in these Terms.</p>
                    </Section>
                    
                     <Section title="3. User Content and Generated Content">
                        <p>You retain all rights to the input you provide to the Service ("Input"). You grant us a worldwide, non-exclusive, royalty-free license to use, process, and transmit your Input to provide the Service to you.</p>
                        <p>As between you and Synapse AI, and to the extent permitted by law, you own the content generated by the AI in response to your Input ("Output"). You are responsible for the Output you generate and its subsequent use. Due to the nature of machine learning, Output may not be unique and other users may receive similar results. We do not guarantee the accuracy, relevance, or quality of the Output.</p>
                    </Section>

                    <Section title="4. Subscriptions and Payment">
                        <p>Our "Pro" plan is offered on a subscription basis. You will be billed in advance on a recurring, periodic basis (either monthly or annually). Subscriptions will automatically renew unless you cancel it or we cancel it.</p>
                        <p>All fees are exclusive of all taxes, levies, or duties imposed by taxing authorities, and you shall be responsible for payment of all such taxes, levies, or duties.</p>
                    </Section>

                    <Section title="5. Prohibited Conduct">
                        <p>You agree not to misuse the Service or help anyone else to do so. This includes, but is not limited to, the following:</p>
                        <ul>
                            <li>Using the Service to generate content that is unlawful, harmful, threatening, abusive, harassing, defamatory, or otherwise objectionable.</li>
                            <li>Attempting to reverse engineer, decompile, or discover the source code of the Service.</li>
                            <li>Using automated systems or software to extract data from the Service (scraping).</li>
                            <li>Interfering with or disrupting the integrity or performance of the Service.</li>
                        </ul>
                    </Section>

                    <Section title="6. Termination">
                        <p>We may terminate or suspend your access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>
                        <p>Upon termination, your right to use the Service will immediately cease. You can cancel your account at any time through your account settings.</p>
                    </Section>
                    
                    <Section title="7. Disclaimers and Limitation of Liability">
                        <p>THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. WE DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>
                        <p>IN NO EVENT SHALL SYNAPSE AI BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES.</p>
                    </Section>

                    <Section title="8. Changes to Terms">
                        <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide reasonable notice of any changes. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.</p>
                    </Section>
                </main>
                
                <footer className="text-center mt-12">
                     <button onClick={() => onNavigate('landing')} className="inline-flex items-center text-slate-300 hover:text-white font-semibold py-2 px-4 rounded-lg transition-colors duration-300">
                        Back to Home
                        <ArrowRightIcon className="w-4 h-4 ml-2" />
                    </button>
                </footer>
            </div>
        </div>
    );
};

export default TermsAndConditions;